--Produtor
CREATE TABLE PRODUTOR (
	CODIGO INTEGER NOT NULL primary key,
	NOME VARCHAR(100) NOT NULL,
	CNPJ VARCHAR(18) NOT NULL
);

--Trade
CREATE TABLE TRADE (
	CODIGO INTEGER NOT NULL primary key,
	NOME VARCHAR(100) NOT NULL,
        CNPJ VARCHAR(18) NOT NULL
);

--Silo
CREATE TABLE SILO (
	CODIGO INTEGER NOT NULL primary key,
	DESCRICAO VARCHAR(100),
	QUANTIDADE INTEGER NOT NULL,
	COD_TRADE INTEGER NOT NULL references TRADE
);


--Produto
CREATE TABLE PRODUTO (
	CODIGO INTEGER NOT NULL primary key,
	DESCRICAO VARCHAR(100) NOT NULL
);

--Contrato
CREATE TABLE CONTRATO (
	CODIGO INTEGER NOT NULL PRIMARY key,
	DATA_CONTRATO DATE NOT NULL,
	COD_PRODUTOR INTEGER NOT NULL references PRODUTOR,
	COD_PRODUTO INTEGER NOT NULL references PRODUTO,
	QUANTIDADE INTEGER NOT NULL,
	COD_TRADE INTEGER NOT NULL references TRADE
);

--Contrato Silo
CREATE TABLE CONTRATO_SILO (
	CODIGO INTEGER NOT NULL primary key,
	COD_CONTRATO INTEGER NOT NULL references CONTRATO,
	COD_SILO INTEGER NOT NULL references SILO,
	QUANTIDADE INTEGER NOT NULL
);